"""empty message

Revision ID: 24f2bbf707e8
Revises: dcfff8778b1c
Create Date: 2020-05-16 18:14:14.358985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f2bbf707e8'
down_revision = 'dcfff8778b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation_sate',
    sa.Column('donations_objects.id', sa.Integer(), nullable=True),
    sa.Column('states_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donations_objects.id'], ['donation_objects.id'], ),
    sa.ForeignKeyConstraint(['states_id'], ['states.id'], ),

    )
    op.create_table('my_donations',
    sa.Column('persons_id', sa.Integer(), nullable=False),
    sa.Column('donations_objects.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donations_objects.id'], ['donation_objects.id'], ),
    sa.ForeignKeyConstraint(['persons_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('persons_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_donations')
    op.drop_table('donation_sate')
    op.drop_table('states')
    # ### end Alembic commands ###
