"""empty message

Revision ID: 97ec8e6172f3
Revises: 566de9eaa630
Create Date: 2020-05-19 14:52:21.376485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ec8e6172f3'
down_revision = '566de9eaa630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_sate', sa.Column('donations_objects_id', sa.Integer(), nullable=True))
    op.drop_constraint('donation_sate_donations_objects.id_fkey', 'donation_sate', type_='foreignkey')
    op.create_foreign_key(None, 'donation_sate', 'donation_objects', ['donations_objects_id'], ['id'])
    op.drop_column('donation_sate', 'donations_objects.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_sate', sa.Column('donations_objects.id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'donation_sate', type_='foreignkey')
    op.create_foreign_key('donation_sate_donations_objects.id_fkey', 'donation_sate', 'donation_objects', ['donations_objects.id'], ['id'])
    op.drop_column('donation_sate', 'donations_objects_id')
    # ### end Alembic commands ###
