"""empty message

Revision ID: dcfff8778b1c
Revises: ecd4c82680c9
Create Date: 2020-05-16 13:21:18.013642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfff8778b1c'
down_revision = 'ecd4c82680c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('persons', sa.Column('login', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'password')
    op.drop_column('persons', 'login')
    op.drop_table('donation_objects')
    # ### end Alembic commands ###
